# Generated by Django 5.0.2 on 2024-02-28 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='gemini_output',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='text_input',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
