# Generated by Django 5.0.2 on 2024-03-03 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatbot_date_remove_chatbot_gemini_output_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('element_id', models.CharField(blank=True, max_length=255, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_type', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
