# Generated by Django 5.0.2 on 2024-03-11 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_remove_chatbot_user_remove_userinteractionlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_question', models.TextField(blank=True, null=True)),
                ('similar_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_answers', to='chat_app.chatbot')),
            ],
        ),
    ]
