# Generated by Django 5.0.2 on 2024-03-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_similaranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('lineno', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmitEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PageViewEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('element_class', models.CharField(blank=True, max_length=255, null=True)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('scrollPosition', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
