# Generated by Django 5.0.2 on 2024-03-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_clickeventlog_errorlog_formsubmiteventlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similaranswer',
            name='similar_question',
        ),
    ]
